### ISSUE TITLE
Floating window not displaying

### ISSUE THREAD

**Issue by Akulen** [matsui54/ddc-nvim-lsp-doc#10] opened 2021-12-08 17:00 UTC
I tried adding this plugin to my configuration for neovim (0.5.1) with ddc, but it doesnt seem to work. When I try to complete a call to a c++ stl function (such as vector.push_back()), there is nothing displayed besides the completion suggestions window
Here is my full config: http://paste.awesom.eu/bNiJ

**Comment by Shougo** [comment] 2021-12-09 01:01
Hi.  Have you read the documentation??

https://github.com/matsui54/ddc-nvim-lsp-doc#ddc-nvim-lsp-doc

> If you use Vim or pum.vim, use denops-popup-preview.vim instead.

Pum.vim is not supported and you have used `pum.vim` in your vimrc.

So it is intended behavior.  You should close the issue.

**Comment by matsui54** [comment] 2021-12-09 02:33
Yes. You can use both signature help and completion documentation feature with this configuration.
```vim
  let g:ddc_nvim_lsp_doc_config = {
        \ 'documentation': {
        \   'enable': v:false,
        \ },
        \ }
  call popup_preview#enable()
  call ddc_nvim_lsp_doc#enable()
```
```

**Closed as completed by matsui54** 2021-12-09 02:33 UTC
